/**
 * Copyright (2018, ) Institute of Software, Chinese Academy of Sciences
 */
package com.github.qcase.webfrk;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * @author wuheng(@iscas.ac.cn)
 * @since   2018/11/24
 * 
 * <p>
 * The {@code ApplicationServer} class is generated by
 * Spring cloud framework. You can invoke the main method
 * to start this program for debugging in development, or
 * running in production
 * 
 * <p>
 * Note: do not modify this class
 */ 
@SpringBootApplication
@MapperScan(value = "com.bocloud.paas.auth")
public class ApplicationServer {

	public static void main(String[] args) {
		SpringApplication.run(ApplicationServer.class, args);
	}
}
