/**
 * Copyright (2018, ) Institute of Software, Chinese Academy of Sciences
 */
package cn.abcsys.faas.application.webfrk;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * @author wuheng(@otcaix.iscas.ac.cn)
 * @since   2018/4/28
 * 
 * <p>
 * The {@code ApplicationServer} class is generated by
 * Spring cloud framework
 */ 
@SpringBootApplication
public class ApplicationServer {

	public static void main(String[] args) {
		SpringApplication.run(ApplicationServer.class, args);
	}
}
